### ISSUE TITLE
Config Settings for UniFi

### ISSUE THREAD

**Issue by ServerKarma** [hacor/unifi-freeradius-ldap#5]
I have been able to get this to start and run ok, however each time that my Radius Server tries to bind, it fails on the inner tunnel due to a trust issue.  I was wondering if you would be able to share the FreeRadius config you used with UniFi?

**Comment by hacor** [comment]
All the config files should be correct in the container itself.
But the fact you have a 'trust' issue does make me think the IP ranges are not set correctly.
Are you sure the `ACCESS_ALLOWED_CIDR` are set correctly? (this should be the IP range of where the login requests occur.
Can you also share some logs so we can better determine where the problem comes from?

**Comment by ServerKarma** [comment]
Will do!
